//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lotery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lotery()
        {
            this.ClubCards = new HashSet<ClubCards>();
            this.EnterpCards = new HashSet<EnterpCards>();
            this.EnterpCards1 = new HashSet<EnterpCards>();
        }
    
        public int C_id { get; set; }
        public byte[] Img { get; set; }
        public Nullable<int> Sum { get; set; }
        public Nullable<int> SumType { get; set; }
        public string Description { get; set; }
        public Nullable<int> EnterpCardId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClubCards> ClubCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnterpCards> EnterpCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnterpCards> EnterpCards1 { get; set; }
    }
}
